CREATE TABLE [dbo].[COLOR](
	[ELEMENTO] [varchar](200) NOT NULL,
	[COLOR] [varchar](200) NOT NULL
)

INSERT INTO COLOR(ELEMENTO, COLOR) VALUES ('MakeFile', 'rgb(251, 0, 0)')
INSERT INTO COLOR(ELEMENTO, COLOR) VALUES ('Servidor Tuxedo', 'rgb(48, 176, 236)')
INSERT INTO COLOR(ELEMENTO, COLOR) VALUES ('Servicio Tuxedo', 'rgb(48, 88, 255)')
INSERT INTO COLOR(ELEMENTO, COLOR) VALUES ('Dependencia', 'rgb(244, 0, 255)')
INSERT INTO COLOR(ELEMENTO, COLOR) VALUES ('Funcion', 'rgb(51, 255, 51)')
INSERT INTO COLOR(ELEMENTO, COLOR) VALUES ('Alias', 'rgb(172, 107, 0)')
INSERT INTO COLOR(ELEMENTO, COLOR) VALUES ('Servicio Core', 'rgb(244, 107, 66)')

CREATE TABLE [dbo].[DEPENDENCIA_FUNCION_CONSUMO](
	[DEPENDENCIA] [varchar](900) NULL,
	[FUNCION] [varchar](400) NULL,
	[SERVICIO_CONSUMIDO] [varchar](400) NULL
)
CREATE NONCLUSTERED INDEX IDX_DEPE_DEPENDENCIA_FUNCION_CONSUMO ON DEPENDENCIA_FUNCION_CONSUMO(DEPENDENCIA)
CREATE NONCLUSTERED INDEX IDX_FUNCION_DEPENDENCIA_FUNCION_CONSUMO ON DEPENDENCIA_FUNCION_CONSUMO(FUNCION)
CREATE NONCLUSTERED INDEX IDX_SERVICIO_DEPENDENCIA_FUNCION_CONSUMO ON DEPENDENCIA_FUNCION_CONSUMO(SERVICIO_CONSUMIDO)

CREATE TABLE [dbo].[MAKE_ERROR](
	[MAKE_ERROR] [varchar](900) NULL
)
CREATE NONCLUSTERED INDEX IDX_MAKE_MAKE_ERROR ON MAKE_ERROR(MAKE_ERROR)

CREATE TABLE [dbo].[MAKE_SERVIDOR](
	[ARCHIVO_MAKE] [varchar](900) NULL,
	[NOMBRE_SERVIDOR] [varchar](400) NULL
)
CREATE NONCLUSTERED INDEX IDX_ARCHIVO_MAKE_MAKE_SERVIDOR ON MAKE_SERVIDOR(ARCHIVO_MAKE)
CREATE NONCLUSTERED INDEX IDX_NOMBRE_SERVIDOR_MAKE_SERVIDOR ON MAKE_SERVIDOR(NOMBRE_SERVIDOR)

CREATE TABLE [dbo].[SERVICIO_ALIAS](
	[ARCHIVO_MAKE] [varchar](900) NULL,
	[SERVICIO] [varchar](200)NULL,
	[ALIAS] [varchar](200) NULL
)
CREATE NONCLUSTERED INDEX IDX_SERVICIO_SERVICIO_ALIAS ON SERVICIO_ALIAS(SERVICIO)
CREATE NONCLUSTERED INDEX IDX_ALIAS_SERVICIO_ALIAS ON SERVICIO_ALIAS(ALIAS)

CREATE TABLE [dbo].[SERVICIO_FUNCION](
	[ARCHIVO_FUENTE] [varchar](900) NULL,
	[SERVICIO] [varchar](200) NULL,
	[FUNCION] [varchar](200) NULL
)
CREATE NONCLUSTERED INDEX IDX_SERVICIO_SERVICIO_FUNCION ON SERVICIO_FUNCION(SERVICIO)
CREATE NONCLUSTERED INDEX IDX_FUNCION_SERVICIO_FUNCION ON SERVICIO_FUNCION(FUNCION)

CREATE TABLE [dbo].[SERVIDOR_DEPENDENCIA](
	[NOMBRE_SERVIDOR] [varchar](400) NULL,
	[DEPENDENCIA] [varchar](900) NULL
)
CREATE NONCLUSTERED INDEX IDX_NOMBRE_SERVIDOR_SERVIDOR_DEPENDENCIA ON SERVIDOR_DEPENDENCIA(NOMBRE_SERVIDOR)
CREATE NONCLUSTERED INDEX IDX_DEPENDENCIA_SERVIDOR_DEPENDENCIA ON SERVIDOR_DEPENDENCIA(DEPENDENCIA)

CREATE TABLE [dbo].[SERVIDOR_SERVICIO](
	[ARCHIVO_FUENTE] [varchar](900) NULL,
	[NOMBRE_SERVIDOR] [varchar](400) NULL,
	[NOMBRE_SERVICIO] [varchar](400) NULL
)
CREATE NONCLUSTERED INDEX IDX_ARCHIVO_FUENTE_SERVIDOR_SERVICIO ON SERVIDOR_SERVICIO(ARCHIVO_FUENTE)
CREATE NONCLUSTERED INDEX IDX_NOMBRE_SERVIDOR_SERVIDOR_SERVICIO ON SERVIDOR_SERVICIO(NOMBRE_SERVIDOR)
CREATE NONCLUSTERED INDEX IDX_NOMBRE_SERVICIO_SERVIDOR_SERVICIO ON SERVIDOR_SERVICIO(NOMBRE_SERVICIO)

CREATE TABLE [dbo].[DEPENDENCIA_FUNCION](
	[DEPENDENCIA] [varchar](900) NULL,
	[FUNCION] [varchar](200) NULL
) 
CREATE NONCLUSTERED INDEX IDX_DEPENDENCIA_DEPENDENCIA_FUNCION ON DEPENDENCIA_FUNCION(DEPENDENCIA ASC)
CREATE NONCLUSTERED INDEX IDX_FUNCION_DEPENDENCIA_FUNCION ON DEPENDENCIA_FUNCION(FUNCION ASC)


CREATE TABLE [dbo].[DEPENDENCIA_FUNCION_FUNCION](
	[DEPENDENCIA] [varchar](900) NULL,
	[FUNCION] [varchar](200) NULL,
	[FUNCION_EJECUTADA] [varchar](200) NULL
)
CREATE NONCLUSTERED INDEX IDX_DEPENDENCIA_DEPENDENCIA_FUNCION_FUNCION ON DEPENDENCIA_FUNCION_FUNCION(DEPENDENCIA ASC)
CREATE NONCLUSTERED INDEX IDX_FUNCION_DEPENDENCIA_FUNCION_FUNCION ON DEPENDENCIA_FUNCION_FUNCION(FUNCION ASC)
CREATE NONCLUSTERED INDEX IDX_FUNCION_EJECUTADA_DEPENDENCIA_FUNCION_FUNCION ON DEPENDENCIA_FUNCION_FUNCION(FUNCION_EJECUTADA ASC)

CREATE TABLE DEPENDENCIA_FUNCION_CORE(
	DEPENDENCIA VARCHAR(900),
	FUNCION VARCHAR(200),
	SERVICIO_CORE VARCHAR(900))
CREATE NONCLUSTERED INDEX IDX_DEPE_DEPENDENCIA_FUNCION_CORE ON DEPENDENCIA_FUNCION_CORE(DEPENDENCIA)
CREATE NONCLUSTERED INDEX IDX_FUNCION_DEPENDENCIA_FUNCION_CORE ON DEPENDENCIA_FUNCION_CORE(FUNCION)
CREATE NONCLUSTERED INDEX IDX_CORE_DEPENDENCIA_FUNCION_CORE ON DEPENDENCIA_FUNCION_CORE(SERVICIO_CORE)

CREATE PROCEDURE [dbo].[AL_ALIAS_SERVICIO]
	@pNOMBRE VARCHAR(200),
	@pRUTA VARCHAR(900),
	@pPATH VARCHAR(900)
AS
BEGIN
SELECT
	A.ARCHIVO_MAKE RUTAREALALIAS,
	DBO.RUTA_RELATIVA(A.ARCHIVO_MAKE) RUTARELATIVAALIAS,
	A.ALIAS NOMBREALIAS,
	B.NOMBRE_SERVICIO NOMBRESERVICIO,
	B.ARCHIVO_FUENTE RUTAREALSERVICIO,
	B.NOMBRE_SERVIDOR NOMBRESERVIDOR,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE) RUTARELATIVASERVICIO
FROM
	SERVICIO_ALIAS A INNER JOIN SERVIDOR_SERVICIO B
	ON A.SERVICIO = B.NOMBRE_SERVICIO
WHERE
	A.ALIAS = @pNOMBRE
	AND A.ARCHIVO_MAKE = @pRUTA
	AND B.ARCHIVO_FUENTE LIKE '%' + @pPATH + '%'
GROUP BY
	A.ARCHIVO_MAKE,
	DBO.RUTA_RELATIVA(A.ARCHIVO_MAKE),
	A.ALIAS,
	B.NOMBRE_SERVICIO,
	B.ARCHIVO_FUENTE,
	B.NOMBRE_SERVIDOR,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE)
END

CREATE PROCEDURE [dbo].[AL_FUNCION_ALIAS]
	@pNOMBRE VARCHAR(200),
	@pRUTA VARCHAR(900)
AS
BEGIN
SELECT
	A.DEPENDENCIA RUTAREALFUNCION,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) RUTARELATIVAFUNCION,
	A.FUNCION NOMBREFUNCION,
	B.ARCHIVO_MAKE RUTAREALALIAS,
	DBO.RUTA_RELATIVA(B.ARCHIVO_MAKE) RUTARELATIVAALIAS,
	B.ALIAS NOMBREALIAS,
	B.SERVICIO
FROM
	DEPENDENCIA_FUNCION_CONSUMO A INNER JOIN SERVICIO_ALIAS B
	ON A.SERVICIO_CONSUMIDO = B.ALIAS
WHERE
	B.ARCHIVO_MAKE = @pRUTA
	AND B.ALIAS = @pNOMBRE
GROUP BY
	A.DEPENDENCIA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA),
	A.FUNCION,
	B.ARCHIVO_MAKE,
	DBO.RUTA_RELATIVA(B.ARCHIVO_MAKE),
	B.ALIAS,
	B.SERVICIO
END

CREATE PROCEDURE [dbo].[CORE_FUNCION_CORE]
	@pNOMBRESERVICIO VARCHAR(200)
AS
BEGIN
SELECT
	DEPENDENCIA RUTAREALFUNCION,
	DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVAFUNCION,
	FUNCION NOMBREFUNCION,
	SERVICIO_CORE NOMBRESERVICIOCORE
FROM
	DEPENDENCIA_FUNCION_CORE
WHERE
	SERVICIO_CORE = @pNOMBRESERVICIO
GROUP BY
	DEPENDENCIA,
	DBO.RUTA_RELATIVA(DEPENDENCIA),
	FUNCION,
	SERVICIO_CORE
END

CREATE PROCEDURE [dbo].[DEP_DEPENDENCIA_FUNCION]
	@pRUTA VARCHAR(900)
AS
BEGIN
SELECT
	DEPENDENCIA RUTAREAL,
	DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVA,
	FUNCION
FROM
	DEPENDENCIA_FUNCION
WHERE
	DEPENDENCIA = @pRUTA
	AND DEPENDENCIA NOT IN(
		SELECT
			ARCHIVO_FUENTE
		FROM
			SERVIDOR_SERVICIO
		)
GROUP BY
	DEPENDENCIA,
	DBO.RUTA_RELATIVA(DEPENDENCIA),
	FUNCION
END

CREATE PROCEDURE [dbo].[DEP_DEPENDENCIA_SERVIDOR]
	@pPATH VARCHAR(900),
	@pRUTADEPENDENCIA VARCHAR(900)
AS
BEGIN
SELECT
	A.NOMBRE_SERVIDOR NOMBRESERVIDOR,
	B.ARCHIVO_FUENTE RUTAREALSERVIDOR,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE) RUTARELATIVASERVIDOR,
	A.DEPENDENCIA RUTAREALDEPENDENCIA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) RUTARELATIVADEPENDENCIA
FROM
	SERVIDOR_DEPENDENCIA A INNER JOIN SERVIDOR_SERVICIO B
	ON A.NOMBRE_SERVIDOR = B.NOMBRE_SERVIDOR
WHERE
	DEPENDENCIA NOT IN(
		SELECT
			ARCHIVO_MAKE
		FROM
			MAKE_SERVIDOR
		WHERE
			NOMBRE_SERVIDOR = A.NOMBRE_SERVIDOR)
	AND A.DEPENDENCIA LIKE '%' + @pPATH + '%' 
	AND B.ARCHIVO_FUENTE LIKE '%' + @pPATH + '%' 
	AND A.DEPENDENCIA = @pRUTADEPENDENCIA
GROUP BY
	A.NOMBRE_SERVIDOR,
	B.ARCHIVO_FUENTE,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE),
	A.DEPENDENCIA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) 
END

CREATE PROCEDURE [dbo].[DEPENDENCIA_DECLARA_FUNCION]
	@pRUTA VARCHAR(900),
	@pFUNCION VARCHAR(200)
AS
BEGIN
	SELECT DISTINCT
		DEPENDENCIA OBJETO,
		'Dependencia' TIPOOBJETO,
		'DECLARA' RELACION,
		FUNCION OBJETO2,
		'Funcion' TIPOOBJETO2,
		DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVA,
		DEPENDENCIA RUTAREAL
	FROM
		DEPENDENCIA_FUNCION
	WHERE
		DEPENDENCIA NOT IN (
			SELECT
				ARCHIVO_FUENTE
			FROM
				SERVIDOR_SERVICIO)
		AND DEPENDENCIA = @pRUTA
		AND FUNCION = @pFUNCION
END

CREATE PROCEDURE [dbo].[DEPENDENCIAS_SERVIDOR] 
	@pNOMBRE VARCHAR(200),
	@pPATH VARCHAR(900)
AS
BEGIN
SELECT
	A.NOMBRE_SERVIDOR NOMBRE_SERVIDOR,
	A.DEPENDENCIA RUTAREAL,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) RUTARELATIVA,
	B.ARCHIVO_FUENTE RUTAREALSERVIDOR,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE) RUTARELATIVASERVIDOR
FROM
	SERVIDOR_DEPENDENCIA A INNER JOIN SERVIDOR_SERVICIO B
	ON A.NOMBRE_SERVIDOR = B.NOMBRE_SERVIDOR
WHERE
	A.DEPENDENCIA LIKE '%' + @pPATH + '%'
	AND A.NOMBRE_SERVIDOR = @pNOMBRE
	AND A.DEPENDENCIA NOT IN(
		SELECT	
			ARCHIVO_MAKE
		FROM
			MAKE_SERVIDOR
		WHERE
			NOMBRE_SERVIDOR = @pNOMBRE)
	AND A.NOMBRE_SERVIDOR = @pNOMBRE
	AND B.ARCHIVO_FUENTE LIKE '%' + @pPATH + '%'
GROUP BY
	A.NOMBRE_SERVIDOR,
	A.DEPENDENCIA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA),
	B.ARCHIVO_FUENTE
END

CREATE PROCEDURE [dbo].[FUN_FUNCION_CORE]
	@pRUTAREALFUNCION VARCHAR(900),
	@pNOMBREFUNCION VARCHAR(200)
AS
BEGIN
	SELECT
		DEPENDENCIA RUTAREALFUNCION,
		DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVAFUNCION,
		FUNCION NOMBREFUNCION,
		SERVICIO_CORE NOMBRESERVICIOCORE
	FROM
		DEPENDENCIA_FUNCION_CORE
	WHERE
		DEPENDENCIA = @pRUTAREALFUNCION
		AND FUNCION = @pNOMBREFUNCION
	GROUP BY
		DEPENDENCIA,
		DBO.RUTA_RELATIVA(DEPENDENCIA),
		FUNCION,
		SERVICIO_CORE
END

CREATE PROCEDURE [dbo].[FUN_SERVICIO_EJECUTA_FUNCION]
	@pPATH VARCHAR(900),
	@pRUTAFUNCION VARCHAR(900),
	@pNOMBREFUNCION VARCHAR(900)
AS
BEGIN
SELECT
	A.ARCHIVO_FUENTE RUTAREALSERVICIO,
	DBO.RUTA_RELATIVA(A.ARCHIVO_FUENTE) RUTARELATIVASERVICIO,
	A.SERVICIO NOMBRESERVICIO,
	C.NOMBRE_SERVIDOR NOMBRESERVIDOR,
	B.DEPENDENCIA RUTAREALFUNCION,
	DBO.RUTA_RELATIVA(B.DEPENDENCIA) RUTARELATIVAFUNCION,
	B.FUNCION NOMBREFUNCION
FROM
	SERVICIO_FUNCION A INNER JOIN (
		SELECT DISTINCT DEPENDENCIA, FUNCION FROM DEPENDENCIA_FUNCION UNION ALL
		SELECT DISTINCT DEPENDENCIA, FUNCION FROM  DEPENDENCIA_FUNCION_CORE) B
	ON A.FUNCION = B.FUNCION INNER JOIN SERVIDOR_SERVICIO C
	ON A.ARCHIVO_FUENTE = C.ARCHIVO_FUENTE
		AND A.SERVICIO = C.NOMBRE_SERVICIO
WHERE
	A.ARCHIVO_FUENTE LIKE '%' + @pPATH + '%'
	AND B.DEPENDENCIA = @pRUTAFUNCION
	AND B.FUNCION = @pNOMBREFUNCION
GROUP BY
	A.ARCHIVO_FUENTE,
	DBO.RUTA_RELATIVA(A.ARCHIVO_FUENTE),
	A.SERVICIO,
	C.NOMBRE_SERVIDOR,
	B.DEPENDENCIA,
	DBO.RUTA_RELATIVA(B.DEPENDENCIA),
	B.FUNCION
END

CREATE PROCEDURE [dbo].[FUNCION_CONSUME_ALIAS]
	@pFUNCION VARCHAR(200),
	@pRUTA VARCHAR(900)
AS
BEGIN
SELECT
	A.DEPENDENCIA RUTAREALFUNCION,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) RUTARELATIVAFUNCION,
	A.FUNCION NOMBREFUNCION,
	A.SERVICIO_CONSUMIDO NOMBREALIAS,
	B.ARCHIVO_MAKE RUTAREALALIAS,
	DBO.RUTA_RELATIVA(B.ARCHIVO_MAKE) RUTARELATIVAALIAS,
	B.SERVICIO
FROM
	DEPENDENCIA_FUNCION_CONSUMO A INNER JOIN SERVICIO_ALIAS B
	ON A.SERVICIO_CONSUMIDO = B.ALIAS
WHERE
	A.DEPENDENCIA = @pRUTA
	AND A.FUNCION = @pFUNCION
GROUP BY
A.DEPENDENCIA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA),
	A.FUNCION ,
	A.SERVICIO_CONSUMIDO,
	B.ARCHIVO_MAKE,
	DBO.RUTA_RELATIVA(B.ARCHIVO_MAKE),
	B.SERVICIO
END

CREATE PROCEDURE [dbo].[FUNCION_CONSUME_SERVICIO]
	@pNOMBRE VARCHAR(200),
	@pRUTA VARCHAR(900)
AS
BEGIN
SELECT
	A.DEPENDENCIA RUTAREALFUNCION,
	A.FUNCION NOMBREFUNCION,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) RUTARELATIVAFUNCION,
	A.SERVICIO_CONSUMIDO NOMBRESERVICIO,
	B.ARCHIVO_FUENTE RUTAREALSERVICIO,
	B.NOMBRE_SERVIDOR NOMBRESERVIDOR,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE) RUTARELATIVASERVICIO
FROM
	DEPENDENCIA_FUNCION_CONSUMO A INNER JOIN SERVIDOR_SERVICIO B
	ON A.SERVICIO_CONSUMIDO = B.NOMBRE_SERVICIO
WHERE
	A.DEPENDENCIA = @pRUTA
	AND A.FUNCION = @pNOMBRE
GROUP BY
	A.DEPENDENCIA,
	A.FUNCION,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA),
	A.SERVICIO_CONSUMIDO,
	B.ARCHIVO_FUENTE,
	B.NOMBRE_SERVIDOR,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE)
END

CREATE PROCEDURE [dbo].[FUNCION_EJECUTA_FUNCION]
	@pNOMBREFUNCION VARCHAR(200),
	@pRUTAFUNCION VARCHAR(900),
	@pPATH VARCHAR(900)
AS
BEGIN
SELECT
	A.FUNCION NOMBREFUNCION,
	A.DEPENDENCIA RUTAREALFUNCION,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) RUTARELATIVAFUNCION,
	B.FUNCION NOMBREFUNCIONEJECUTADA,
	B.DEPENDENCIA RUTAREALFUNCIONEJECUTADA,
	DBO.RUTA_RELATIVA(B.DEPENDENCIA) RUTARELATIVAFUNCIONEJECUTADA
FROM
	DEPENDENCIA_FUNCION_FUNCION A INNER JOIN DEPENDENCIA_FUNCION B
	ON A.FUNCION_EJECUTADA = B.FUNCION
WHERE
	A.FUNCION = @pNOMBREFUNCION
	AND A.DEPENDENCIA = @pRUTAFUNCION
	AND B.DEPENDENCIA LIKE '%' + @pPATH + '%'
GROUP BY
	A.FUNCION,
	A.DEPENDENCIA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA),
	B.FUNCION,
	B.DEPENDENCIA,
	DBO.RUTA_RELATIVA(B.DEPENDENCIA)
END

CREATE PROCEDURE [dbo].[FUNCION_ES_EJECUTADA_FUNCION]
	@pNOMBRE VARCHAR(200),
	@pRUTA VARCHAR(900),
	@pPATH VARCHAR(900)
AS
BEGIN
SELECT
	A.DEPENDENCIA RUTAREALFUNCIONEJECUTORA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) RUTARELATIVAFUNCIONEJECUTORA,
	A.FUNCION NOMBREFUNCIONEJECUTORA,
	B.FUNCION NOMBREFUNCION,
	B.DEPENDENCIA RUTAREALFUNCION,
	DBO.RUTA_RELATIVA(B.DEPENDENCIA) RUTARELATIVAFUNCION
FROM
	DEPENDENCIA_FUNCION_FUNCION A INNER JOIN DEPENDENCIA_FUNCION B
	ON A.FUNCION_EJECUTADA = B.FUNCION
WHERE
	A.FUNCION_EJECUTADA = @pNOMBRE
	AND B.DEPENDENCIA = @pRUTA
	AND A.DEPENDENCIA LIKE '%' + @pPATH + '%'
	AND B.DEPENDENCIA LIKE '%' + @pPATH + '%'
	AND A.DEPENDENCIA NOT IN(
		SELECT DISTINCT
			ARCHIVO_FUENTE
		FROM
			SERVIDOR_SERVICIO)
GROUP BY
	A.DEPENDENCIA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA),
	A.FUNCION,
	B.FUNCION,
	B.DEPENDENCIA,
	DBO.RUTA_RELATIVA(B.DEPENDENCIA)
END

CREATE PROCEDURE [dbo].[MAKE_GENERA_SERVIDOR] 
	@pRUTASERVIDOR VARCHAR(900),
	@pPATHSERVIDOR VARCHAR(900)
AS
BEGIN
SELECT
	A.ARCHIVO_MAKE RUTAREALMAKE,
	DBO.RUTA_RELATIVA(A.ARCHIVO_MAKE) RUTARELATIVAMAKE,
	B.NOMBRE_SERVIDOR,
	B.ARCHIVO_FUENTE RUTAREALSERVIDOR,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE) RUTARELATIVASERVIDOR
FROM
	MAKE_SERVIDOR A INNER JOIN SERVIDOR_SERVICIO B
	ON A.NOMBRE_SERVIDOR = B.NOMBRE_SERVIDOR

WHERE
	B.ARCHIVO_FUENTE = @pRUTASERVIDOR
	AND A.ARCHIVO_MAKE LIKE '%' + @pPATHSERVIDOR + '%'
GROUP BY
	A.ARCHIVO_MAKE,
	B.NOMBRE_SERVIDOR,
	B.ARCHIVO_FUENTE
END

CREATE PROCEDURE [dbo].[SEL_ALIASES]
AS
BEGIN
SELECT
	ARCHIVO_MAKE RUTAREAL,
	DBO.JS_PATH(ARCHIVO_MAKE) JSPATH,
	DBO.RUTA_RELATIVA(ARCHIVO_MAKE) RUTARELATIVA,
	SERVICIO,
	ALIAS
FROM
	SERVICIO_ALIAS
GROUP BY
	ARCHIVO_MAKE,
	DBO.JS_PATH(ARCHIVO_MAKE),
	DBO.RUTA_RELATIVA(ARCHIVO_MAKE),
	SERVICIO,
	ALIAS
END

CREATE PROCEDURE [dbo].[SEL_DEPENDENCIAS]
AS
BEGIN
SELECT DISTINCT
	*
FROM(
	SELECT DISTINCT
		DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVA,
		DBO.JS_PATH(DEPENDENCIA) RUTAREAL
	FROM
		SERVIDOR_DEPENDENCIA
	UNION ALL
	SELECT DISTINCT
		DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVA,
		DBO.JS_PATH(DEPENDENCIA) RUTAREAL
	FROM
		DEPENDENCIA_FUNCION_CONSUMO
	) A

END


CREATE PROCEDURE [dbo].[SEL_FUNCIONES]
AS
BEGIN
SELECT DISTINCT
	DBO.JS_PATH(RUTAREAL) RUTAREAL,
	RUTARELATIVA,
	FUNCION
FROM(
	SELECT DISTINCT
		DEPENDENCIA RUTAREAL,
		DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVA,
		FUNCION
	FROM
		DEPENDENCIA_FUNCION_CONSUMO
	WHERE
		DEPENDENCIA NOT IN(
			SELECT
				ARCHIVO_FUENTE
			FROM
				SERVIDOR_SERVICIO
		)
	UNION ALL
	SELECT DISTINCT
		DEPENDENCIA RUTAREAL,
		DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVA,
		FUNCION
	FROM
		DEPENDENCIA_FUNCION	
	WHERE
		DEPENDENCIA NOT IN(
			SELECT
				ARCHIVO_FUENTE
			FROM
				SERVIDOR_SERVICIO
		)
	UNION ALL
	SELECT DISTINCT
		DEPENDENCIA RUTAREAL,
		DBO.RUTA_RELATIVA(DEPENDENCIA) RUTARELATIVA,
		FUNCION
	FROM
		DEPENDENCIA_FUNCION_CORE
	)A

END

CREATE PROCEDURE [dbo].[SEL_MAKE_SERVIDOR]
	@pARCHIVOMAKE VARCHAR(900),
	@pFOLDER VARCHAR(900)
AS
BEGIN
SELECT
	DBO.JS_PATH(A.ARCHIVO_MAKE) RUTAREALMAKE,
	DBO.RUTA_RELATIVA(A.ARCHIVO_MAKE) RUTARELATIVAMAKE,
	B.NOMBRE_SERVIDOR,
	C.ARCHIVO_FUENTE RUTAREALSERVIDOR,
	DBO.RUTA_RELATIVA(C.ARCHIVO_FUENTE) RUTARELATIVASERVIDOR
FROM
	MAKE_SERVIDOR A INNER JOIN SERVIDOR_DEPENDENCIA B
	ON A.NOMBRE_SERVIDOR = B.NOMBRE_SERVIDOR INNER JOIN SERVIDOR_SERVICIO C
	ON B.DEPENDENCIA = C.ARCHIVO_FUENTE
WHERE
	A.ARCHIVO_MAKE = @pARCHIVOMAKE
	AND B.DEPENDENCIA LIKE '%' + @pFOLDER + '%' 
GROUP BY
	A.ARCHIVO_MAKE,
	B.NOMBRE_SERVIDOR,
	C.ARCHIVO_FUENTE
END

CREATE PROCEDURE [dbo].[SEL_MAKEFILES]
AS
BEGIN
	SELECT DISTINCT
		DBO.RUTA_RELATIVA(ARCHIVO_MAKE) RUTARELATIVA,
		ARCHIVO_MAKE RUTAREAL,
		DBO.JS_PATH(ARCHIVO_MAKE) JSPATH
	FROM
		MAKE_SERVIDOR
END

CREATE PROCEDURE [dbo].[SEL_SERVICIOS]
AS
BEGIN
	SELECT DISTINCT
		NOMBRE_SERVIDOR,
		NOMBRE_SERVICIO,
		ARCHIVO_FUENTE RUTAREAL,
		DBO.JS_PATH(ARCHIVO_FUENTE) JSPATH,
		DBO.RUTA_RELATIVA(ARCHIVO_FUENTE) RUTARELATIVA
	FROM
		SERVIDOR_SERVICIO
END

CREATE PROCEDURE [dbo].[SEL_SERVICIOS_CORE]
AS
BEGIN
	SELECT
		SERVICIO
	FROM
		SERVICIO_CORE
END

CREATE PROCEDURE [dbo].[SEL_SERVIDORES_TUXEDO]
AS
BEGIN
SELECT
	ARCHIVO_FUENTE RUTAREAL,
	DBO.JS_PATH(ARCHIVO_FUENTE) JSPATH,
	NOMBRE_SERVIDOR NOMBRE,
	DBO.RUTA_RELATIVA(ARCHIVO_FUENTE) RUTARELATIVA
FROM
	SERVIDOR_SERVICIO
GROUP BY
	ARCHIVO_FUENTE,
	DBO.JS_PATH(ARCHIVO_FUENTE),
	NOMBRE_SERVIDOR,
	DBO.RUTA_RELATIVA(ARCHIVO_FUENTE)
END

CREATE PROCEDURE [dbo].[SERV_FUNCION_CONSUME_SERVICIO]
	@pNOMBRESERVICIO VARCHAR(200),
	@pARCHIVOFUENTE VARCHAR(900),
	@pPATH VARCHAR(900)
AS
BEGIN
SELECT
	A.DEPENDENCIA RUTAREALFUNCION,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA) RUTARELATIVAFUNCION,
	A.FUNCION,
	B.ARCHIVO_FUENTE RUTAREALSERVICIO,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE) RUTARELATIVASERVICIO,
	B.NOMBRE_SERVICIO,
	B.NOMBRE_SERVIDOR
FROM
	DEPENDENCIA_FUNCION_CONSUMO A INNER JOIN SERVIDOR_SERVICIO B
	ON A.SERVICIO_CONSUMIDO = B.NOMBRE_SERVICIO
WHERE
	B.NOMBRE_SERVICIO = @pNOMBRESERVICIO
	AND B.ARCHIVO_FUENTE = @pARCHIVOFUENTE
GROUP BY
	A.DEPENDENCIA,
	DBO.RUTA_RELATIVA(A.DEPENDENCIA),
	A.FUNCION,
	B.ARCHIVO_FUENTE,
	DBO.RUTA_RELATIVA(B.ARCHIVO_FUENTE),
	B.NOMBRE_SERVICIO,
	B.NOMBRE_SERVIDOR
END

CREATE PROCEDURE [dbo].[SERV_SERVICIO_ALIAS]
	@pNOMBRESERVICIO VARCHAR(200),
	@pPATH VARCHAR(900)
AS
BEGIN
SELECT
	A.SERVICIO NOMBRESERVICIO,
	A.ALIAS NOMBREALIAS,
	C.NOMBRE_SERVIDOR NOMBRESERVIDOR,
	A.ARCHIVO_MAKE RUTAREALALIAS,
	DBO.RUTA_RELATIVA(A.ARCHIVO_MAKE) RUTARELATIVAALIAS,
	C.ARCHIVO_FUENTE RUTAREALSERVICIO,
	DBO.RUTA_RELATIVA(C.ARCHIVO_FUENTE) RUTARELATIVASERVICIO
FROM
	SERVICIO_ALIAS A INNER JOIN MAKE_SERVIDOR B
	ON A.ARCHIVO_MAKE = B.ARCHIVO_MAKE INNER JOIN SERVIDOR_SERVICIO C
	ON B.NOMBRE_SERVIDOR = C.NOMBRE_SERVIDOR
WHERE
	A.SERVICIO = @pNOMBRESERVICIO
	AND C.NOMBRE_SERVICIO = @pNOMBRESERVICIO
	AND A.ARCHIVO_MAKE LIKE '%' + @pPATH + '%'
	AND C.ARCHIVO_FUENTE LIKE '%' + @pPATH + '%'
END

CREATE PROCEDURE [dbo].[SERV_SERVICIO_EJECUTA_FUNCION]
	@pNOMBRESERVICIO VARCHAR(200),
	@pRUTAREALSERVICIO VARCHAR(900),
	@pPATH VARCHAR(900)
AS
BEGIN
SELECT
	A.ARCHIVO_FUENTE RUTAREALSERVICIO,
	DBO.RUTA_RELATIVA(A.ARCHIVO_FUENTE) RUTARELATIVASERVICIO,
	A.SERVICIO NOMBRESERVICIO,
	C.NOMBRE_SERVIDOR,
	B.FUNCION,
	B.DEPENDENCIA RUTAREALFUNCION,
	DBO.RUTA_RELATIVA(B.DEPENDENCIA) RUTARELATIVAFUNCION
FROM
	SERVICIO_FUNCION A INNER JOIN DEPENDENCIA_FUNCION B
	ON A.FUNCION = B.FUNCION INNER JOIN SERVIDOR_SERVICIO C
	ON A.SERVICIO = C.NOMBRE_SERVICIO
		AND C.ARCHIVO_FUENTE LIKE '%' + @pPATH + '%'
WHERE
	A.SERVICIO = @pNOMBRESERVICIO
	AND A.ARCHIVO_FUENTE = @pRUTAREALSERVICIO
	AND B.DEPENDENCIA LIKE '%' + @pPATH + '%'
GROUP BY
	A.ARCHIVO_FUENTE,
	A.SERVICIO,
	C.NOMBRE_SERVIDOR,
	B.FUNCION,
	B.DEPENDENCIA,
	DBO.RUTA_RELATIVA(A.ARCHIVO_FUENTE),
	DBO.RUTA_RELATIVA(B.DEPENDENCIA)
END

CREATE PROCEDURE [dbo].[SERVICIO_EJECUTA_FUNCION]
	@pRUTA VARCHAR(900),
	@pFUNCION VARCHAR(200)
AS
BEGIN
	SELECT DISTINCT
		A.NOMBRE_SERVIDOR SERVIDOR,
		A.NOMBRE_SERVICIO OBJETO,
		'Servicio Tuxedo' TIPOOBJETO,
		'EJECUTA' RELACION,
		C.FUNCION OBJETO2,
		'Funcion' TIPOOBJETO2,
		C.DEPENDENCIA RUTAREAL,
		DBO.RUTA_RELATIVA(C.DEPENDENCIA) RUTARELATIVA
	FROM
		SERVIDOR_SERVICIO A INNER JOIN SERVICIO_FUNCION B
		ON A.NOMBRE_SERVICIO = B.SERVICIO INNER JOIN DEPENDENCIA_FUNCION C
		ON B.FUNCION = C.FUNCION
			AND C.DEPENDENCIA IN(
				SELECT
					DEPENDENCIA
				FROM
					SERVIDOR_DEPENDENCIA
				WHERE
					NOMBRE_SERVIDOR = A.NOMBRE_SERVIDOR
				)
	WHERE
		C.DEPENDENCIA NOT IN(
			SELECT
				ARCHIVO_FUENTE
			FROM
				SERVIDOR_SERVICIO
			GROUP BY
				ARCHIVO_FUENTE
		)
		AND C.DEPENDENCIA = @pRUTA
		AND C.FUNCION = @pFUNCION
END

CREATE PROCEDURE [dbo].[SERVIDOR_EXPONE_SERVICIO]
	@pARCHIVO VARCHAR(200),
	@pSERVICIO VARCHAR(200)
AS
BEGIN
SELECT DISTINCT
		NOMBRE_SERVIDOR,
		NOMBRE_SERVICIO,
		ARCHIVO_FUENTE RUTAREAL,
		DBO.RUTA_RELATIVA(ARCHIVO_FUENTE) RUTARELATIVA
	FROM
		SERVIDOR_SERVICIO
	WHERE
		NOMBRE_SERVICIO = @pSERVICIO
		AND ARCHIVO_FUENTE = @pARCHIVO
END

CREATE PROCEDURE [dbo].[SVR_SERVIDOR_SERVICIO]
	@pRUTASERVIDOR VARCHAR(900)
AS
BEGIN
SELECT
	NOMBRE_SERVIDOR,
	NOMBRE_SERVICIO,
	ARCHIVO_FUENTE,
	DBO.RUTA_RELATIVA(ARCHIVO_FUENTE)RUTARELATIVA
FROM
	SERVIDOR_SERVICIO
WHERE
	ARCHIVO_FUENTE = @pRUTASERVIDOR
END

CREATE FUNCTION [dbo].[ES_ALIAS](
	@pALIAS VARCHAR(200))
RETURNS VARCHAR(200)
AS
BEGIN
	DECLARE @pSALIDA VARCHAR(200)
	SELECT
		@pSALIDA = SERVICIO
	FROM
		SERVICIO_ALIAS
	WHERE
		ALIAS = @pALIAS
RETURN @pSALIDA
END

CREATE FUNCTION [dbo].[JS_PATH](
	@pRUTA VARCHAR(900)
)
RETURNS VARCHAR(900)
AS
BEGIN
	DECLARE @pJSPATH VARCHAR(900)
	SELECT @pJSPATH = REPLACE(@pRUTA, '\', '\\')
RETURN @pJSPATH
END

CREATE FUNCTION [dbo].[RUTA_RELATIVA](
	@pRUTA VARCHAR(900))
RETURNS VARCHAR(900)
AS
BEGIN
	DECLARE @pSALIDA VARCHAR(900)
	SELECT @pSALIDA = REPLACE(REPLACE(@pRUTA, 'D:\Fuentes\Cmontenegro', ''), '\', '/')
	RETURN @pSALIDA
END